###

GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts/
Content-Type: application/json

{
  "image": "path/to/image.jpg",
  "caption": "This is a test post",
  "createdAt": "2023-08-31T00:00:00.000Z",
  "_id": "unique-post-idd",
  "user": "user-id",
  "comments": [],
  "likes": 0,
  "location": "Test Location!",
  "petName": "Buddy",
  "when": "2023-07-31T00:00:00.000Z"
}
###